language: android

os:
  - linux
  - osx

osx_image: xcode9.1

before_install:
- .ci/safe_run.sh .ci/hosts/$TRAVIS_OS_NAME/before_install.sh
- .ci/safe_run.sh .ci/targets/$RHO_TARGET/before_install.sh

install:
- .ci/safe_run.sh .ci/hosts/$TRAVIS_OS_NAME/install.sh
- .ci/safe_run.sh .ci/targets/$RHO_TARGET/install.sh
- gem install rest-client listen zip
- rvm install 2.3.4

script:
- cd $TRAVIS_BUILD_DIR
#- ci/hosts/$TRAVIS_OS_NAME/build_rhoruby.sh #TODO
- .ci/safe_run.sh .ci/targets/$RHO_TARGET/pre_gem.sh
- rake gem
- rvm use 2.3.4
- rvm gemset create rhodes
- rvm gemset use rhodes
- travis_wait 30 gem install ./rhodes-$(cat ./version).gem --no-document
- .ci/safe_run.sh ./ci/targets/$RHO_TARGET/rho_setup.sh
- git clone $(.ci/app_repo.rb) $HOME/$RHO_APP
- cd $HOME/$RHO_APP/$(.ci/app_build_root.rb)
- rake run:$RHO_TARGET

android:
  components:
  - tools
  - platform-tools
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository    
  - addon-google_apis-google-19
  - android-19
  - sdkmanager tools
  
env:
  - RHO_TARGET=android
  - RHO_TARGET=iphone
  - RHO_TARGET=rhosimulator
  - RHO_TARGET=win32
  - RHO-TARGET=osx
  - RHO-TARGET=linux
  - RHO_APP=auto_common_spec
  - RHO_APP=framework_spec
  - RHO_APP=sas
  - RHO_APP=kitchenSinkJS
  - RHO_APP=kitchenSinkRuby
  - RHO_APP=push_spec
  - RHO_APP=rhoconnect-client_spec

matrix:
  exclude:
  - env: RHO_TARGET=win32               #not supported on TRAVIS
  - env: RHO_TARGET=osx                 #TODO - desktop app build
  - env: RHO_TARGET=linux               #TODO - desktop app build
  - env: RHO_APP=push_spec              #TODO - support push specs
  - env: RHO_APP=rhoconnect-client_spec #TODO - support rhoconnect client specs
  