language: android

rvm:
- 2.4.3

install:
- gem install rest-client listen zip

script:
- rake gem
- rvm gemset create rhodes
- rvm gemset use rhodes
- travis_wait 30 gem install ./rhodes-$(cat ./version).gem --verbose
- printf "$JAVA_HOME\n$ANDROID_HOME\n$ANDROID_HOME/ndk-bundle\n\n\n\n\n" | rhodes-setup
- git clone https://github.com/rhomobile/RMS-Testing.git $HOME/RMS-Testing
- cd $HOME/RMS-Testing/auto/feature_def/auto_common_spec && rake run:android

android:
  components:
    - tools
    - platform-tools
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19
    - sys-img-x86-android-19
