before_install:
- $TRAVIS_BUILD_DIR/.ci/safe_run.sh $TRAVIS_BUILD_DIR/.ci/hosts/$TRAVIS_OS_NAME/before_install.sh
- $TRAVIS_BUILD_DIR/.ci/safe_run.sh $TRAVIS_BUILD_DIR/.ci/targets/$RHO_TARGET/before_install.sh

install:
- $TRAVIS_BUILD_DIR/.ci/safe_run.sh $TRAVIS_BUILD_DIR/.ci/hosts/$TRAVIS_OS_NAME/install.sh
- $TRAVIS_BUILD_DIR/.ci/safe_run.sh $TRAVIS_BUILD_DIR/.ci/targets/$RHO_TARGET/install.sh
- rvm install 2.3.4
- rvm use 2.3.4
- gem install rest-client listen zip

script:
- cd $TRAVIS_BUILD_DIR
#- ci/hosts/$TRAVIS_OS_NAME/build_rhoruby.sh #TODO
- $TRAVIS_BUILD_DIR/.ci/safe_run.sh $TRAVIS_BUILD_DIR/.ci/targets/$RHO_TARGET/pre_gem.sh
- rake gem
- rvm gemset create rhodes
- rvm gemset use rhodes
- travis_wait 30 gem install ./rhodes-$(cat ./version).gem --no-document
- $TRAVIS_BUILD_DIR/.ci/safe_run.sh $TRAVIS_BUILD_DIR/./ci/targets/$RHO_TARGET/rho_setup.sh
- git clone $(.ci/app_repo.rb) $HOME/$RHO_APP
- cd $HOME/$RHO_APP/$(.ci/app_build_root.rb)
- rake run:$RHO_TARGET
  
android:
  components:
  - tools
  - platform-tools
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository    
  - addon-google_apis-google-19
  - android-19
  - sdkmanager tools

osx_image: xcode9.1

matrix:
  include:
  - language: android
    os: linux
    env: RHO_TARGET="android"    RHO_APP="auto_common_spec"

  - language: android
    os: linux
    env: RHO_TARGET="android"    RHO_APP="framework_spec"

  - language: android
    os: linux
    env: RHO_TARGET="android"    RHO_APP="sas"

  - language: android
    os: linux
    env: RHO_TARGET="android"    RHO_APP="kitchenSinkJS"

  - language: android
    os: linux
    env: RHO_TARGET="android"    RHO_APP="kitchenSinkRuby"

  - language: objective-c
    os: osx
    env: RHO_TARGET="iphone"    RHO_APP="auto_common_spec"

  - language: objective-c
    os: osx
    env: RHO_TARGET="iphone"    RHO_APP="framework_spec"

  - language: objective-c
    os: osx
    env: RHO_TARGET="iphone"    RHO_APP="sas"

  - language: objective-c
    os: osx
    env: RHO_TARGET="iphone"    RHO_APP="kitchenSinkJS"

  - language: objective-c
    os: osx
    env: RHO_TARGET="iphone"    RHO_APP="kitchenSinkRuby"

  - language: objective-c
    os: osx
    env: RHO_TARGET="rhosimulator"    RHO_APP="auto_common_spec"

  - language: objective-c
    os: osx
    env: RHO_TARGET="rhosimulator"    RHO_APP="framework_spec"

  - language: objective-c
    os: osx
    env: RHO_TARGET="rhosimulator"    RHO_APP="sas"

  - language: objective-c
    os: osx
    env: RHO_TARGET="rhosimulator"    RHO_APP="kitchenSinkJS"

  - language: objective-c
    os: osx
    env: RHO_TARGET="rhosimulator"    RHO_APP="kitchenSinkRuby"

  #  - RHO_TARGET="rhosimulator"    RHO_APP="push_spec"
  #  - RHO_TARGET="rhosimulator"    RHO_APP="rhoconnect-client_spec"  
