before_install:
  
- $TRAVIS_BUILD_DIR/.ci/safe_run.sh $TRAVIS_BUILD_DIR/.ci/hosts/$TRAVIS_OS_NAME/before_install.sh
- $TRAVIS_BUILD_DIR/.ci/safe_run.sh $TRAVIS_BUILD_DIR/.ci/targets/$RHO_TARGET/before_install.sh

install:
- ANDROID_NDK_HOME="${HOME}/android-ndk-r${NDK_NUMBER}"
- $TRAVIS_BUILD_DIR/.ci/safe_run.sh $TRAVIS_BUILD_DIR/.ci/check_cache_and_install_ruby.sh
- rvm use $RHO_RUBY
- |
  if [[ -z $(rvm gemset list | grep rhodes) ]]; then
    rvm gemset create rhodes;
  fi
- rvm gemset use rhodes
#- $TRAVIS_BUILD_DIR/.ci/safe_run.sh $TRAVIS_BUILD_DIR/.ci/check_cache_and_install_gems.sh
- bundle install
- $TRAVIS_BUILD_DIR/.ci/safe_run.sh $TRAVIS_BUILD_DIR/.ci/hosts/$TRAVIS_OS_NAME/install.sh
- $TRAVIS_BUILD_DIR/.ci/safe_run.sh $TRAVIS_BUILD_DIR/.ci/targets/$RHO_TARGET/install.sh

script:
- ANDROID_NDK_HOME="${HOME}/android-ndk-r${NDK_NUMBER}"
- rvm list
- rvm use $RHO_RUBY
- rvm gemset list
- rvm gemset use rhodes
- gem install bundler
- gem list

- cd $TRAVIS_BUILD_DIR
#- .ci/hosts/$TRAVIS_OS_NAME/build_rhoruby.sh #TODO
- $TRAVIS_BUILD_DIR/.ci/safe_run.sh $TRAVIS_BUILD_DIR/.ci/targets/$RHO_TARGET/pre_gem.sh
- $TRAVIS_BUILD_DIR/lib/build/buildgem.rb
- travis_wait 30 gem install ./rhodes-$(cat ./version).gem
- $TRAVIS_BUILD_DIR/.ci/safe_run.sh $TRAVIS_BUILD_DIR/.ci/targets/$RHO_TARGET/rho_setup.sh
- .ci/install_rhoconnect-client.sh
- |
  if [[ -n $RHO_TAU_EXTENSIONS ]]; then
    .ci/install_rho-tau-extensions.sh;
  fi
- $TRAVIS_BUILD_DIR/.ci/safe_run.sh $TRAVIS_BUILD_DIR/.ci/targets/$RHO_TARGET/post_gem.sh

- cd $HOME
- rhodes app vanilla_rhodes_app
- cd vanilla_rhodes_app && rhodes extension testext && cd ..
- rhodes jsapp vanilla_rhodes_jsapp
- rhodes nodejsapp vanilla_rhodes_nodejsapp
- cd $TRAVIS_BUILD_DIR

- |
  if [[ -n $RHO_APP ]]; then
    git clone $(.ci/app_repo.rb) $HOME/$RHO_APP;
    cd $HOME/$RHO_APP/$(.ci/app_build_root.rb);
  fi

- |
  if [[ -z $SKIP_BUILD ]]; then
    $TRAVIS_BUILD_DIR/.ci/safe_run.sh $TRAVIS_BUILD_DIR/.ci/targets/$RHO_TARGET/build_artefact_for_deploy.sh;
  fi
#TODO: change this to run specs in auto mode and collect results
- |
  if [[ -z $SKIP_TESTS ]]; then
    travis_wait 45 $TRAVIS_BUILD_DIR/.ci/safe_run.sh $TRAVIS_BUILD_DIR/.ci/targets/$RHO_TARGET/$RHO_RUNNER_SCRIPT;
  fi

#cache:
#  directories:
#    - $HOME/.rvm

before_cache:
  - echo Y | gem uninstall rhodes -a -I

before_deploy:
- mkdir $BUILD_ARTEFACTS_DIR
- "$TRAVIS_BUILD_DIR/.ci/safe_run.sh $TRAVIS_BUILD_DIR/.ci/targets/$RHO_TARGET/before_deploy.sh"
deploy:
  provider: s3
  edge: true
  bucket: tau-autobuilds
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  skip_cleanup: true
  local_dir: "$BUILD_ARTEFACTS_DIR"
  upload-dir: '$S3_DEPLOY_DIR/$S3_JOB_DIR-$RHO_TARGET-$RHO_APP'
  acl: public_read
  region: eu-central-1
  on:
    all_branches: true

android:
  components:
  - tools
  - platform-tools
  - sdkmanager tools
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - build-tools-26.0.1
  - android-26
  - android-${RHO_ANDROID_LEVEL:-19}
  - addon-google_apis-google-${RHO_ANDROID_LEVEL:-19}
#  - sys-img-x86-android-${RHO_ANDROID_LEVEL:-19}
  - sys-img-armeabi-v7a-android-${RHO_ANDROID_LEVEL:-19}

env:
  global:
  - BUILD_ARTEFACTS_DIR=$HOME/build_artefacts
  - S3_JOB_DIR="$TRAVIS_COMMIT"/"$TRAVIS_OS_NAME"
  - S3_DEPLOY_DIR="$TRAVIS_REPO_SLUG"/"$TRAVIS_BRANCH"
  - QTDIR="$HOME/Qt5.13.2/5.13.2/clang_64"
  - RHO_RUBY="${RHO_RUBY:=$RUBY_VERSION}"
  - ANDROID_ABIS="${ANDROID_ABIS:=arm,aarch64}"

#osx_image: xcode9.1

#addons:
#  apt:
#    packages:
#    - bridge-utils
#    - libpulse0
#    - libvirt-bin
#    - qemu-kvm
#    - virtinst
#    - ubuntu-vm-builder    

#addons:
#  apt:
#    packages:
#    - bridge-utils
#    - libpulse0
#    - libvirt-bin
#    - qemu-kvm
#    - virtinst
#    - ubuntu-vm-builder    

matrix:
  include:

#ios targets  
  - language: objective-c
    os: osx
    #osx_image: xcode11.4
    env: RHO_TARGET="rhosimulator_osx"  CACHE_NAME="RVM_OSX"  RHO_RUNNER_SCRIPT="run_app_on_simulator.sh" RHO_RUBY="2.7.0"

  - language: objective-c
    os: osx
    #osx_image: xcode11.4
    env: RHO_TARGET="iphone"    RHO_APP="auto_common_spec"  CACHE_NAME="RVM_OSX"  RHO_RUNNER_SCRIPT="run_test_on_simulator.sh" RHO_RUBY="2.6.5"

  - language: objective-c
    os: osx
    #osx_image: xcode11.4
    env: RHO_TARGET="iphone"    RHO_APP="framework_spec"  CACHE_NAME="RVM_OSX"  RHO_RUNNER_SCRIPT="run_test_on_simulator.sh" RHO_RUBY="2.7.0"

  - language: objective-c
    os: osx
    osx_image: xcode11.4
    env: RHO_TARGET="iphone"    RHO_APP="sas"  CACHE_NAME="RVM_OSX"  RHO_RUNNER_SCRIPT="run_app_on_simulator.sh"

  - language: objective-c
    os: osx
    osx_image: xcode11.4
    env: RHO_TARGET="iphone"    RHO_APP="universal_push_example"  CACHE_NAME="RVM_OSX"  RHO_RUNNER_SCRIPT="run_app_on_simulator.sh"

  - language: objective-c
    os: osx
    osx_image: xcode11.4
    env: RHO_TARGET="iphone"    RHO_APP="rhodes_fcm_test"  CACHE_NAME="RVM_OSX"  RHO_RUNNER_SCRIPT="run_app_on_simulator.sh"


  - language: objective-c
    os: osx
    osx_image: xcode11.4
    env: RHO_TARGET="iphone"    RHO_APP="sas"  CACHE_NAME="RVM_OSX"  RHO_RUNNER_SCRIPT="run_app_on_simulator.sh"

  - language: objective-c
    os: osx
    osx_image: xcode11.4
    env: RHO_TARGET="iphone"    RHO_APP="universal_push_example"  CACHE_NAME="RVM_OSX"  RHO_RUNNER_SCRIPT="run_app_on_simulator.sh"

  - language: objective-c
    os: osx
    osx_image: xcode11.4
    env: RHO_TARGET="iphone"    RHO_APP="rhodes_fcm_test"  CACHE_NAME="RVM_OSX"  RHO_RUNNER_SCRIPT="run_app_on_simulator.sh"

  - language: objective-c
    os: osx
    osx_image: xcode11.4
    env: RHO_TARGET="iphone"    RHO_APP="todo-nodejs"  CACHE_NAME="RVM_OSX"  RHO_RUNNER_SCRIPT="run_app_on_simulator.sh" RHO_TAU_EXTENSIONS="yes"

  - language: objective-c
    os: osx
    osx_image: xcode11.4
    env: RHO_TARGET="iphone_native_lib"    RHO_APP="rhodes_lib_examples"  CACHE_NAME="RVM_OSX2"  RHO_RUNNER_SCRIPT="run_app_on_simulator.sh"

  - language: objective-c
    os: osx
    osx_image: xcode11.4
    env: RHO_TARGET="iphone_native_lib"    RHO_APP="rhodes_lib_examples"  CACHE_NAME="RVM_OSX2"  RHO_RUNNER_SCRIPT="run_app_on_simulator.sh"

#linux targets 
  - language: c++
    os: linux
    env: RHO_TARGET="linux"    RHO_APP="auto_common_spec"  CACHE_NAME="RVM_LINUX"  MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"  RHO_RUNNER_SCRIPT="run_app_on_simulator.sh" RHO_RUBY="2.5.7"
    dist: bionic
    addons:
      apt:
        packages:
          - debhelper
          - fakeroot

  - language: c++
    os: linux
    env: RHO_TARGET="linux"    RHO_APP="framework_spec"  CACHE_NAME="RVM_LINUX"  MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"  RHO_RUNNER_SCRIPT="run_app_on_simulator.sh"
    dist: bionic
    addons:
      apt:
        packages:
          - debhelper
          - fakeroot

#android targets
  - language: android
    os: linux
    env: RHO_TARGET="android"    RHO_APP="framework_spec" CACHE_NAME="RVM_LINUX" RHO_ANDROID_LEVEL="21" NDK_NUMBER="20"  RHO_RUNNER_SCRIPT="run_test_on_simulator.sh" RHO_RUBY="2.5.7" ANDROID_ABIS="arm,x86"

  - language: android
    os: linux
    env: RHO_TARGET="android"    RHO_APP="auto_common_spec"  CACHE_NAME="RVM_LINUX" RHO_ANDROID_LEVEL="21" NDK_NUMBER="20"  RHO_RUNNER_SCRIPT="run_test_on_simulator.sh" RHO_RUBY="2.6.5"

  - language: android
    os: linux
    env: RHO_TARGET="android"    RHO_APP="auto_common_spec" CACHE_NAME="RVM_LINUX" RHO_ANDROID_LEVEL="21" NDK_NUMBER="20"  RHO_RUNNER_SCRIPT="run_test_on_simulator.sh"  RUBY_VERSION="2.7.0"

  - language: android
    os: linux
    env: RHO_TARGET="android"    RHO_APP="sas" CACHE_NAME="RVM_LINUX" RHO_ANDROID_LEVEL="21" NDK_NUMBER="20"  SKIP_TESTS=1

  - language: android
    os: linux
    env: RHO_TARGET="android"    RHO_APP="rhodes_fcm_test" CACHE_NAME="RVM_LINUX" RHO_ANDROID_LEVEL="21" NDK_NUMBER="20"  SKIP_TESTS=1

#  - language: android
#    os: linux
#    env: RHO_TARGET="android"    RHO_APP="todo-nodejs" CACHE_NAME="RVM_LINUX" RHO_ANDROID_LEVEL="21" NDK_NUMBER="20" RHO_TAU_EXTENSIONS="yes" SKIP_TESTS=1

#  - language: android
#    os: linux
#    env: RHO_TARGET="android_native_lib"    RHO_APP="rhodes_lib_examples" CACHE_NAME="RVM_LINUX" RHO_ANDROID_LEVEL="21" NDK_NUMBER="20"  SKIP_TESTS=1


  # - language: android
  #   os: linux
  #   env: RHO_TARGET="android"    RHO_APP="auto_common_spec" CACHE_NAME="RVM_LINUX" RHO_ANDROID_LEVEL="24" NDK_NUMBER="17c"

  - language: android
    os: linux
    env: RHO_TARGET="android"    RHO_APP="inventory_demo" CACHE_NAME="RVM_LINUX" RHO_ANDROID_LEVEL="24" NDK_NUMBER="20" SKIP_TESTS=1
