language: android

rvm:
- 2.3.4

before_install:
  #get Android NDK
- wget https://dl.google.com/android/repository/android-ndk-r12b-linux-x86_64.zip -O $HOME/ndk.zip
- unzip -q $HOME/ndk.zip -d $HOME
- export ANDROID_NDK_HOME=$HOME/android-ndk-r12b
- rm $HOME/ndk.zip

install:
- gem install rest-client listen zip

script:
- rake gem
- rvm install 2.3.4
- rvm use 2.3.4
- rvm gemset create rhodes
- rvm gemset use rhodes
- travis_wait 30 gem install ./rhodes-$(cat ./version).gem --no-document
- printf "$JAVA_HOME\n$ANDROID_HOME\n$ANDROID_NDK_HOME\n\n\n\n\n\n\n" | rhodes-setup
- git clone https://github.com/rhomobile/RMS-Testing.git $HOME/RMS-Testing
- cd $HOME/RMS-Testing/auto/feature_def/auto_common_spec && rake run:android

android:
  components:
    - tools
    - platform-tools
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19
    - sys-img-x86-android-19
