version: '{branch}.{build}'
platform: x86
clone_folder: C:\TAU\rhodes
environment:
  GITHUB_APPVEYOR_TOKEN:
    secure: 7Vs1V9MjrPNKV9vHNkNN07BJjaAs1WEF/F9Mb+dQLGSwnFK9lpstnJvGyawWFkdJ
  matrix:
    - wm_kitchensinkJS:
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      QTDIR: C:\Qt\5.6\msvc2013
      testable_application_repository: https://github.com/tauplatform/kitchensinkJS.git
      test_app_folder: C:\TAU\kitchensinkJS\
      build_command: "device:wm:production"
      app_name: KitchensinkJS
      target_os: wm
      target_artefact_path: C:\TAU\kitchensinkJS\bin\target\wm\
      target_os_wm: wm
      
    - win32_rhosimulator:
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      QTDIR: C:\Qt\5.13\msvc2017
      testable_application_repository: https://github.com/rhomobile/RMS-Testing.git
      test_app_folder: C:\TAU\RMS-Testing\
      test_app_subfolder: auto\feature_def\auto_common_spec\
      build_command: build:win32:rhosimulator_to C:/TAU/rhosim/RhoSimulator.zip
      app_name: RhoSimulator
      target_os: win32
      target_artefact_path: C:\TAU\rhosim\
      target_artefact_file_name: RhoSimulator.zip

    - win32_auto_common_spec_2019:
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      QTDIR: C:\Qt\5.15\msvc2019
      testable_application_repository: https://github.com/rhomobile/RMS-Testing.git
      test_app_folder: C:\TAU\RMS-Testing\
      test_app_subfolder: auto\feature_def\auto_common_spec\
      build_command: "device:win32:production"
      after_build_command: "run:win32:spec"
      app_name: auto_common_spec
      target_os: win32
      target_artefact_path: C:\TAU\RMS-Testing\auto\feature_def\auto_common_spec\bin\target\win32\
      target_artefact_file_name: auto_common_spec-setup.exe
    
    - win32_framework_spec_2019:
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      QTDIR: C:\Qt\5.15\msvc2019
      testable_application_repository: https://github.com/rhomobile/RMS-Testing.git
      test_app_folder: C:\TAU\RMS-Testing\
      test_app_subfolder: auto\feature_def\framework_spec\
      build_command: "run:win32:spec"
      #after_build_command: "run:win32:spec"
      app_name: framework_spec
      target_os: win32
      target_artefact_path: C:\TAU\RMS-Testing\auto\feature_def\framework_spec\bin\target\win32\
      #target_artefact_file_name: framework_spec-setup.exe


    - win32_auto_common_spec_2017:
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      QTDIR: C:\Qt\5.13\msvc2017
      testable_application_repository: https://github.com/rhomobile/RMS-Testing.git
      test_app_folder: C:\TAU\RMS-Testing\
      test_app_subfolder: auto\feature_def\auto_common_spec\
      build_command: "device:win32:production"
      after_build_command: "run:win32:spec"
      app_name: auto_common_spec
      target_os: win32
      target_artefact_path: C:\TAU\RMS-Testing\auto\feature_def\auto_common_spec\bin\target\win32\
      target_artefact_file_name: auto_common_spec-setup.exe
    
    - win32_framework_spec_2017:
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      QTDIR: C:\Qt\5.13\msvc2017
      testable_application_repository: https://github.com/rhomobile/RMS-Testing.git
      test_app_folder: C:\TAU\RMS-Testing\
      test_app_subfolder: auto\feature_def\framework_spec\
      build_command: "run:win32:spec"
      #after_build_command: "run:win32:spec"
      app_name: framework_spec
      target_os: win32
      target_artefact_path: C:\TAU\RMS-Testing\auto\feature_def\framework_spec\bin\target\win32\
      #target_artefact_file_name: framework_spec-setup.exe

    - win32_auto_common_spec_2015:
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      QTDIR: C:\Qt\5.9\msvc2015
      testable_application_repository: https://github.com/rhomobile/RMS-Testing.git
      test_app_folder: C:\TAU\RMS-Testing\
      test_app_subfolder: auto\feature_def\auto_common_spec\
      build_command: "device:win32:production"
      after_build_command: "run:win32:spec"
      app_name: auto_common_spec
      target_os: win32
      target_artefact_path: C:\TAU\RMS-Testing\auto\feature_def\auto_common_spec\bin\target\win32\
      target_artefact_file_name: auto_common_spec-setup.exe
    
    - win32_framework_spec_2015:
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      QTDIR: C:\Qt\5.9\msvc2015
      testable_application_repository: https://github.com/rhomobile/RMS-Testing.git
      test_app_folder: C:\TAU\RMS-Testing\
      test_app_subfolder: auto\feature_def\framework_spec\
      build_command: "run:win32:spec"
      #after_build_command: "run:win32:spec"
      app_name: framework_spec
      target_os: win32
      target_artefact_path: C:\TAU\RMS-Testing\auto\feature_def\framework_spec\bin\target\win32\
      #target_artefact_file_name: framework_spec-setup.exe

    - win32_kitchensinkJS:
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      QTDIR: C:\Qt\5.13\msvc2017
      testable_application_repository: https://github.com/tauplatform/kitchensinkJS.git
      test_app_folder: C:\TAU\kitchensinkJS\
      build_command: "device:win32:production"
      app_name: KitchensinkJS
      target_os: win32
      target_artefact_path: C:\TAU\kitchensinkJS\bin\target\win32\
      target_artefact_file_name: kitchensinkJS-setup.exe

    - win32_kitchensinkRuby:
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      QTDIR: C:\Qt\5.13\msvc2017
      testable_application_repository: https://github.com/tauplatform/kitchensinkRuby.git
      test_app_folder: C:\TAU\kitchensinkRuby\
      build_command: "device:win32:production"
      app_name: KitchensinkRuby
      target_os: win32
      target_artefact_path: C:\TAU\kitchensinkRuby\bin\target\win32\
      target_artefact_file_name: kitchensinkRuby-setup.exe

    - win32_rho_ruby:
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      QTDIR: C:\Qt\5.13\msvc2017
      testable_application_repository: https://github.com/rhomobile/RMS-Testing.git
      test_app_folder: C:\TAU\RMS-Testing\
      test_app_subfolder: auto\feature_def\auto_common_spec\
      pre_build_command: "build:rhoruby"
      build_command: "device:win32:production"
      after_build_command: "run:win32:spec"
      app_name: auto_common_spec
      target_os: win32
    

build: off

install:
  - set PATH=C:\Ruby26\bin;%PATH%
  - set RAKEOPT=-rdevkit
  - md C:\TAU\downloads
  - cd C:\TAU\downloads

  - IF DEFINED target_os_wm curl -fsS -o WM6.5ProSDK.msi http://files.tau-technologies.com/wince/WM6.5ProSDK.msi
  - IF DEFINED target_os_wm WM6.5ProSDK.msi /qn /quiet /norestart
  - IF DEFINED target_os_wm timeout 300
#  - gem install rest-client --no-document -f
#  - gem install listen --no-document -f
#  - gem install zip --no-document -f
#  - gem install net-scp --no-document -f
#  - gem install bundler --quiet --no-ri --no-rdoc -f
#  - bundler --version
  
before_test:
   
  #- IF DEFINED target_os_wm dism /online /Disable-Feature /FeatureName:Internet-Explorer-Optional-amd64 /Quiet

  #- IF DEFINED target_os_wm curl -fsS -o aip.zip http://files.tau-technologies.com/wince/aip.zip
  #- IF DEFINED target_os_wm 7z x aip.zip -y
  #- IF DEFINED target_os_wm timeout 10  
  
  #- IF DEFINED target_os_wm curl -fsS -o 30XXC50BxxPS010403.exe http://files.tau-technologies.com/wince/30XXC50BxxPS010403.exe
  #- IF DEFINED target_os_wm "C:\TAU\downloads\Advanced Installer 17.7 Portable\App\Advanced Installer\bin\x64\RepackagerCLI.exe" /ProductLanguage "1033" /SetupPath "C:\TAU\downloads\30XXC50BxxPS010403.exe" /UiAutomation /Configuration "Default"
  #- IF DEFINED target_os_wm timeout 10
  
  #- IF DEFINED target_os_wm curl -fsS -o EMDK-C-020701.exe http://files.tau-technologies.com/wince/EMDK-C-020701.exe
  #- IF DEFINED target_os_wm "C:\TAU\downloads\Advanced Installer 17.7 Portable\App\Advanced Installer\bin\x64\RepackagerCLI.exe" /ProductLanguage "1033" /SetupPath "EMDK-C-020701.exe" /UiAutomation /Configuration "Default"
  #- IF DEFINED target_os_wm timeout 10



  #- IF DEFINED target_os_wm curl -fsS -o EMDK.msi http://files.tau-technologies.com/wince/rebuild/EMDK.msi
  #- IF DEFINED target_os_wm EMDK.msi /passive
  #- IF DEFINED target_os_wm timeout 10
  
  #- IF DEFINED target_os_wm curl -fsS -o SDK.msi http://files.tau-technologies.com/wince/rebuild/SDK.msi
  #- IF DEFINED target_os_wm SDK.msi /passive
  #- IF DEFINED target_os_wm timeout 10
  
  - ruby -v
  - gem -v
  - bundle -v
  - cp rhobuild.yml.example rhobuild.yml
  - ruby C:\TAU\rhodes\lib\build\buildgem.rb
  - set /P BUILD_VERSION=<version
  - gem install rhodes-%BUILD_VERSION%.gem --no-document -f

  - git clone -b master https://github.com/rhomobile/rhoconnect-client.git C:\TAU\rhoconnect-client
  - cd C:\TAU\rhoconnect-client
  - rake gem:make_gem
  - set /P BUILD_VERSION_RHOCONNECT=<version
  - gem install rhoconnect-client-%BUILD_VERSION_RHOCONNECT%.gem --no-document -f
 
  - git clone https://%GITHUB_APPVEYOR_TOKEN%:x-oauth-basic@github.com/tauplatform/rho-tau-extensions.git C:\TAU\rho-tau-extensions
  - cd C:\TAU\rho-tau-extensions
  - rake gem
  - set /P BUILD_VERSION_RHOTAU=<version
  - gem install rho-tau-extensions-%BUILD_VERSION_RHOTAU%.gem --no-document -f



  - cd C:\TAU\
  - rmdir /Q /S downloads
  - rmdir /Q /S rhodes
  - rmdir /Q /S rhoconnect-client
  - rmdir /Q /S rho-tau-extensions

test_script:
  - git clone -b master %testable_application_repository% %test_app_folder%
  - cd %test_app_folder%
  - IF DEFINED test_app_subfolder cd %test_app_subfolder%
  - rake clean:win32
  #- rake clean:uwp
  - IF DEFINED pre_build_command rake %pre_build_command% --trace
  - rake %build_command% --trace
  - IF DEFINED after_build_command rake %after_build_command%
  - md C:\TAU\rhodes\target\
  - IF DEFINED target_artefact_file_name copy %target_artefact_path%%target_artefact_file_name% C:\TAU\rhodes\target\
  - cd C:\TAU\rhodes\target\
  - dir
  - echo %APPVEYOR_REPO_NAME%/%APPVEYOR_REPO_BRANCH%/%APPVEYOR_REPO_COMMIT%/appveyor-%APPVEYOR_BUILD_NUMBER%.%APPVEYOR_JOB_NUMBER%_win32-%target_os%-%app_name%
  - cd C:\TAU\rhodes\
  
artifacts: 
  - path: .\target\
    name: '${target_artefact_file_name}'

deploy:
  - provider: S3
    access_key_id:  
      secure: j0N6vl5f9UckCbJkHmZiXNuFphMI3cud+NDTCQm/I2c=
    secret_access_key:
      secure: WzHfCbltmZTLnQxLo5/3BzBLHLnuiMIK6aDkoB10by58eOngCcTKvHJUGbtkfcsp
    bucket: tau-autobuilds
    region: eu-central-1
    folder: '$(APPVEYOR_REPO_NAME)/$(APPVEYOR_REPO_BRANCH)/$(APPVEYOR_REPO_COMMIT)/$(target_os)-$(app_name)'
    artifact: /.*/
    unzip: true
    set_public: true
    max_error_retry: 5