name: rhomobile

variables:
- name: BUILD_DIR
  value: $(Build.Repository.LocalPath)
- name: TRAVIS_BUILD_DIR
  value: $(Build.Repository.LocalPath)
- name: OS_NAME
  value: osx
- name: RHO_TARGET
  value: rhosimulator_osx
- name: RHO_RUNNER_SCRIPT
  value: run_app_on_simulator.sh
- name: RHO_RUBY
  value: ruby-2.7.4
- name: ruby_version
  value: '2.7.4'

stages:  
  - stage: build
    jobs:
      - job: build
        pool:
          vmImage: 'macOS-10.14'
        steps:
        - task: UseRubyVersion@0
          inputs:
            versionSpec: $(ruby_version)
            
        - script: $BUILD_DIR/.ci/azure-build.sh
