name: rhomobile

variables:
- name: BUILD_DIR
  value: $(Build.Repository.LocalPath)
- name: OS_NAME
  value: osx
- name: RHO_TARGET
  value: rhosimulator_osx
- name: RHO_RUNNER_SCRIPT
  value: run_app_on_simulator.sh
- name: RHO_RUBY
  value: ruby-2.7.0

stages:  
  - stage: build
    jobs:
      - job: build
        steps:
        - script: $BUILD_DIR/.ci/azure-build.sh
