name: rhomobile
stages:
  - stage: before_install
    jobs:
      - job: setup_for_host
        steps:
          - script: $TRAVIS_BUILD_DIR/.ci/safe_run.sh $TRAVIS_BUILD_DIR/.ci/hosts/$TRAVIS_OS_NAME/before_install.sh
      - job: setup_for_target
        steps:
          - script: $TRAVIS_BUILD_DIR/.ci/safe_run.sh $TRAVIS_BUILD_DIR/.ci/targets/$RHO_TARGET/before_install.sh

  - stage: install
    jobs:
      - job:
        steps:
          #install Ruby version specified in RHO_RUBY env var ( system Ruby by default )
          - script: $TRAVIS_BUILD_DIR/.ci/safe_run.sh $TRAVIS_BUILD_DIR/.ci/check_cache_and_install_ruby.sh
          - script: rvm use $RHO_RUBY
          # run target-specific and host-specific install scripts ( for instance download and install NDK/SDK for Android targets)
          - script: $TRAVIS_BUILD_DIR/.ci/safe_run.sh $TRAVIS_BUILD_DIR/.ci/hosts/$TRAVIS_OS_NAME/install.sh
          - script: $TRAVIS_BUILD_DIR/.ci/safe_run.sh $TRAVIS_BUILD_DIR/.ci/targets/$RHO_TARGET/install.sh
          
#  - stage: build
#  - stage: before_deploy
#  - stage: deploy
