#sdk: ../..
sdkversion: 4.0.0
name: javascript_api_spec
version: 1.0
vendor: rhomobile
build: debug
bbver: 6.0
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator6.0
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.javascriptapispec
  BundleURLScheme: javascriptapispec
wp:
  productid: '5faf0f80-64b4-0130-981a-3c075408a837'
symbian:
  uid: '0xe6d52260'
android:
  version: 2.1

extensions: ["json"] #, "barcode"]
