sdk: "../.."
sdkversion: 4.1.0
name: prebuild_ruby
version: 1.0
vendor: rhomobile
build: release
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphoneos7.1
  provisionprofile:
  codesignidentity: iPhone Developer
  entitlements: ""
  BundleIdentifier: com.rhomobile.prebuildruby
  BundleURLScheme: prebuildruby
wp8:
  productid: '6d2eb150-a391-0131-e3c3-482a1411841f'
android:
  manifest_template: 'AndroidManifest.erb'
  version: 2.3.3

wm:
  #sdk: "MC3000c50b (ARMV4I)"
  #sdk: "Windows Mobile 6.5.3 Professional DTK (ARMV4I)"

extensions: ["rhoconnect-client"]
