sdk: "<%=@sdk_path%>"
sdkversion: <%=Rhodes::VERSION%>
name: <%=@app_name%>
version: 1.2.2
vendor: rhomobile
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: Debug
  sdk: iphonesimulator3.0
  codesignidentity:
  entitlements:
extensions: ["extension-name-here", "second-extension-name"]
