#sdk: "<%=@sdk_path%>"
sdkversion: <%=Rhodes::VERSION%>
name: <%=@app_name%>
version: 1.0
vendor: rhomobile
build: debug
bbver: 6.0
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator6.0
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.<%=@app_name_cleared%>
  BundleURLScheme: <%=@app_name_cleared%>
wp:
  productid: '<%=@productid%>'
symbian:
  uid: '<%=@uid%>'
android:
  version: 2.3.3

extensions: [<%=@rhoconnectclient_ext%>]
