#sdk: "<%=@sdk_path%>"
sdkversion: <%=Rhodes::VERSION%>
name: <%=@app_name%>
version: 1.0
vendor: rhomobile
build: debug
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator7.1
  provisionprofile:
  codesignidentity: iPhone Developer
  entitlements: ""
  BundleIdentifier: com.rhomobile.<%=@app_name_cleared%>
  BundleURLScheme: <%=@app_name_cleared%>
wp8:
  productid: '<%=@productid%>'
android:
  manifest_template: 'AndroidManifest.erb'
  version: 2.3.3
  #logcatFilter: APP:I

wm:
  #sdk: "MC3000c50b (ARMV4I)"
  #sdk: "Windows Mobile 6.5.3 Professional DTK (ARMV4I)"

extensions: [<%=@rhoconnectclient_ext%>]
