sdk: ../../.. 
sdkversion: 3.5.0
name: rhoconnect_push_client
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator7.1
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.rhoconnectpushclient
  BundleURLScheme: rhoconnectpushclient
wp:
  productid: '80b879d0-16fc-0130-39e9-3c0754090a18'
symbian:
  uid: '0xe77b6fc3'
android:
  version: 2.3.3

paths:
  extensions: /Users/alexepifanoff/repos/Motorola-Extensions/extensions

extensions: ["json", "rhoconnect-client", "rhoconnect-push"]
