--- 
name: phone_spec
bbver: 5.0
sdk: /Users/crystax/work/rhomobile/rhodes
applog: rholog.txt
version: 1.0.0
vendor: rhomobile
sdkversion: 1.4
wmsdk: "Windows Mobile 6 Professional SDK (ARMV4I)"
iphone: 
  sdk: iphonesimulator4.0
  entitlements: ""
  codesignidentity: ""
  configuration: Release
  extensions: ["barcode"]
  
android:
  mapping: enabled
  capabilities:
    - network_state
    - pim
    
  extensions: ["barcode"]
  
wm:
  extensions: ["barcode"]
  
bb:
  extensions: ["barcode"]
      
capabilities:
  - push
     
extensions: ["json", "rhoxml", "rhospec", "crypt"]  

